### PR TITLE
changed google-oauth-plugin version to 0.7

### PR DESCRIPTION
**Pull request by craigatgoogle**

### CODE REVIEW

**Comment by craigatgoogle** [comment]
Fix for https://issues.jenkins-ci.org/browse/JENKINS-55606

**Comment by jglick** [comment]
```
org.apache.maven.project.InvalidProjectModelException: Some problems were encountered while processing the POMs:

[ERROR] 'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is /usr/lib/jvm/java-8-jdk/jre/../lib/tools.jar @ io.sundr:sundr-codegen:[unknown-version], C:\Jenkins\workspace\le-kubernetes-engine-plugin_PR-4@tmp\m2repo\io\sundr\sundr-codegen\0.9.2\sundr-codegen-0.9.2.pom, line 54, column 19
```

In fact this POM is bad (will only work on certain Debian/Ubuntu flavors using the OpenJDK 8 packages):

```xml
    <dependency>
      <groupId>com.sun</groupId>
      <artifactId>tools</artifactId>
      <version>1.7</version>
      <scope>system</scope>
      <systemPath>/usr/lib/jvm/java-8-jdk/jre/../lib/tools.jar</systemPath>
    </dependency>
```

`mvn dependency:tree` includes

```
[INFO] +- com.github.kubernetes-client.java:client-java:jar:-client-java-parent-4.0.0-beta1-g8469451-30:compile
[INFO] |  +- com.github.kubernetes-client.java:client-java-api:jar:-client-java-parent-4.0.0-beta1-g8469451-30:compile
[INFO] |  |  +- io.sundr:builder-annotations:jar:0.9.2:compile
[INFO] |  |  |  +- io.sundr:sundr-core:jar:0.9.2:compile
[INFO] |  |  |  +- io.sundr:sundr-codegen:jar:0.9.2:compile
[INFO] |  |  |  \- io.sundr:resourcecify-annotations:jar:0.9.2:compile
```

Used [here](https://github.com/kubernetes-client/java/blob/43a48b09cb242680e0d5c3cc77680ec766c5df91/kubernetes/pom.xml#L133) or [here](https://github.com/kubernetes-client/java/blob/2df55efe6347f60978981682fdc3b2c60c5b5431/kubernetes/build.gradle#L102).

Looks like this was fixed in https://github.com/sundrio/sundrio/pull/118 so I suppose you want to update the sundrio in `<dependencyManagement>` here, or upstream in `kubernetes-client/java`. Or simply `<exclude>` the `sundr-codegen` dep which I doubt is an actual runtime dependency to begin with, though [this](https://github.com/sundrio/sundrio/blob/master/annotations/builder/pom.xml#L51-L55) claims it is (perhaps a msunderstanding of Maven dependency scopes).

**Comment by craigatgoogle** [comment]
Thanks @jglick that helps a great deal!

**Comment by jglick** [comment]
```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Jenkins/workspace/le-kubernetes-engine-plugin_PR-4/target/test-classes/expectedKubeConfig.yml
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at com.google.jenkins.plugins.k8sengine.KubeConfigTest.testToYamlReturnsProperly(KubeConfigTest.java:108)
```

suggests a mistake in the test. Indeed it is assuming that `URL.file` is a filesystem path, which is nonsense (even on Linux this will fail if for example the workspace path contains a space). Maybe try

```diff
-            FileSystems.getDefault()
-                .getPath(
-                    this.getClass()
-                        .getClassLoader()
-                        .getResource("expectedKubeConfig.yml")
-                        .getFile()));
+           Path.get(KubeConfigTest.class.getResource("/expectedKubeConfig.yml").toUri()));
```

**Pull request closed without merging**
